import pkg from '@prisma/client';
const { PrismaClient } = pkg;
const prisma = new PrismaClient();
const ORDER = 'd8beec9d-417b-4056-81c4-49569d65f845';
const demoId = '9c110942-38de-41b4-88aa-55da6f58de30';
const o = await prisma.order.findUnique({ where: { id: ORDER }, select: { userId: true } });
console.log('ORIGINAL_USERID=' + o.userId);
await prisma.order.update({ where: { id: ORDER }, data: { userId: demoId } });
console.log('Lent to demo user.');
await prisma.$disconnect();
